// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > packages/shared/src/types/database.ts

export interface Database {
  public: {
    Tables: {
      // User Management Tables
      users: {
        Row: {
          id: string;
          email: string;
          user_type: 'client' | 'host' | 'operator' | 'admin' | 'pos';
          status: 'active' | 'inactive' | 'suspended';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          user_type: 'client' | 'host' | 'operator' | 'admin' | 'pos';
          status?: 'active' | 'inactive' | 'suspended';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          user_type?: 'client' | 'host' | 'operator' | 'admin' | 'pos';
          status?: 'active' | 'inactive' | 'suspended';
          updated_at?: string;
        };
      };

      user_profiles: {
        Row: {
          id: string;
          user_id: string;
          first_name: string;
          last_name: string;
          phone: string | null;
          avatar_url: string | null;
          date_of_birth: string | null;
          address: string | null;
          discount_eligibility: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          first_name: string;
          last_name: string;
          phone?: string | null;
          avatar_url?: string | null;
          date_of_birth?: string | null;
          address?: string | null;
          discount_eligibility?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          first_name?: string;
          last_name?: string;
          phone?: string | null;
          avatar_url?: string | null;
          date_of_birth?: string | null;
          address?: string | null;
          discount_eligibility?: string[] | null;
          updated_at?: string;
        };
      };

      user_groups: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          operator_id: string | null;
          permissions: any; // JSON object
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          operator_id?: string | null;
          permissions: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
          permissions?: any;
          updated_at?: string;
        };
      };

      // Parking Hierarchy Tables
      locations: {
        Row: {
          id: string;
          name: string;
          type: 'hosted' | 'street' | 'facility';
          operator_id: string;
          address: any; // JSON object
          coordinates: any; // JSON object
          settings: any; // JSON object
          pricing_config: any | null; // JSON object
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: 'hosted' | 'street' | 'facility';
          operator_id: string;
          address: any;
          coordinates: any;
          settings?: any;
          pricing_config?: any | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          type?: 'hosted' | 'street' | 'facility';
          address?: any;
          coordinates?: any;
          settings?: any;
          pricing_config?: any | null;
          updated_at?: string;
        };
      };

      sections: {
        Row: {
          id: string;
          location_id: string;
          name: string;
          pricing_config: any | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          location_id: string;
          name: string;
          pricing_config?: any | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          pricing_config?: any | null;
          updated_at?: string;
        };
      };

      zones: {
        Row: {
          id: string;
          section_id: string;
          name: string;
          pricing_config: any | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          section_id: string;
          name: string;
          pricing_config?: any | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          pricing_config?: any | null;
          updated_at?: string;
        };
      };

      parking_spots: {
        Row: {
          id: string;
          zone_id: string;
          number: string;
          type: string;
          status: 'available' | 'occupied' | 'reserved' | 'maintenance';
          coordinates: any; // JSON object
          pricing_config: any | null;
          amenities: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          zone_id: string;
          number: string;
          type: string;
          status?: 'available' | 'occupied' | 'reserved' | 'maintenance';
          coordinates: any;
          pricing_config?: any | null;
          amenities?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          number?: string;
          type?: string;
          status?: 'available' | 'occupied' | 'reserved' | 'maintenance';
          coordinates?: any;
          pricing_config?: any | null;
          amenities?: string[] | null;
          updated_at?: string;
        };
      };

      // Booking and Transaction Tables
      bookings: {
        Row: {
          id: string;
          user_id: string;
          spot_id: string;
          vehicle_id: string;
          start_time: string;
          end_time: string;
          status:
            | 'pending'
            | 'confirmed'
            | 'active'
            | 'completed'
            | 'cancelled';
          payment_status: 'pending' | 'paid' | 'refunded';
          amount: number;
          discounts: any | null; // JSON array
          vat_amount: number;
          total_amount: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          spot_id: string;
          vehicle_id: string;
          start_time: string;
          end_time: string;
          status?:
            | 'pending'
            | 'confirmed'
            | 'active'
            | 'completed'
            | 'cancelled';
          payment_status?: 'pending' | 'paid' | 'refunded';
          amount: number;
          discounts?: any | null;
          vat_amount?: number;
          total_amount: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?:
            | 'pending'
            | 'confirmed'
            | 'active'
            | 'completed'
            | 'cancelled';
          payment_status?: 'pending' | 'paid' | 'refunded';
          end_time?: string;
          updated_at?: string;
        };
      };

      // Vehicle Management
      vehicles: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          brand: string;
          model: string;
          year: number;
          color: string;
          plate_number: string;
          is_primary: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          brand: string;
          model: string;
          year: number;
          color: string;
          plate_number: string;
          is_primary?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          type?: string;
          brand?: string;
          model?: string;
          year?: number;
          color?: string;
          plate_number?: string;
          is_primary?: boolean;
          updated_at?: string;
        };
      };

      // Messaging System
      conversations: {
        Row: {
          id: string;
          participants: string[];
          type: 'user_host' | 'user_operator' | 'user_support';
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          participants: string[];
          type: 'user_host' | 'user_operator' | 'user_support';
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          is_active?: boolean;
          updated_at?: string;
        };
      };

      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          receiver_id: string;
          content: string;
          type: 'text' | 'image' | 'file';
          is_encrypted: boolean;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          sender_id: string;
          receiver_id: string;
          content: string;
          type?: 'text' | 'image' | 'file';
          is_encrypted?: boolean;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          read_at?: string | null;
        };
      };

      // Rating and Review System
      ratings: {
        Row: {
          id: string;
          booking_id: string;
          rater_id: string;
          rated_id: string;
          rated_type: 'spot' | 'host' | 'operator' | 'user';
          score: number;
          review: string | null;
          photos: string[] | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          rater_id: string;
          rated_id: string;
          rated_type: 'spot' | 'host' | 'operator' | 'user';
          score: number;
          review?: string | null;
          photos?: string[] | null;
          created_at?: string;
        };
        Update: {
          score?: number;
          review?: string | null;
          photos?: string[] | null;
        };
      };

      // Advertisement System
      advertisements: {
        Row: {
          id: string;
          title: string;
          content: any; // JSON object
          target_location: string;
          target_type: 'section' | 'zone';
          schedule: any; // JSON object
          budget: number;
          status: 'pending' | 'approved' | 'active' | 'paused' | 'completed';
          metrics: any | null; // JSON object
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          content: any;
          target_location: string;
          target_type: 'section' | 'zone';
          schedule: any;
          budget: number;
          status?: 'pending' | 'approved' | 'active' | 'paused' | 'completed';
          metrics?: any | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          title?: string;
          content?: any;
          schedule?: any;
          budget?: number;
          status?: 'pending' | 'approved' | 'active' | 'paused' | 'completed';
          metrics?: any | null;
          updated_at?: string;
        };
      };

      // Enhanced Discount System
      discount_rules: {
        Row: {
          id: string;
          name: string;
          type: string;
          percentage: number;
          is_vat_exempt: boolean;
          conditions: any;
          operator_id: string | null;
          is_active: boolean;
          created_by: string;
          approved_by: string | null;
          approved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: string;
          percentage: number;
          is_vat_exempt?: boolean;
          conditions?: any;
          operator_id?: string | null;
          is_active?: boolean;
          created_by: string;
          approved_by?: string | null;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          type?: string;
          percentage?: number;
          is_vat_exempt?: boolean;
          conditions?: any;
          is_active?: boolean;
          approved_by?: string | null;
          approved_at?: string | null;
          updated_at?: string;
        };
      };

      vat_config: {
        Row: {
          id: string;
          name: string;
          rate: number;
          is_default: boolean;
          operator_id: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          rate: number;
          is_default?: boolean;
          operator_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          rate?: number;
          is_default?: boolean;
          is_active?: boolean;
          updated_at?: string;
        };
      };

      discount_applications: {
        Row: {
          id: string;
          booking_id: string;
          discount_rule_id: string;
          original_amount: number;
          discount_amount: number;
          final_amount: number;
          vat_exempted: boolean;
          applied_by: string;
          verification_document_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          discount_rule_id: string;
          original_amount: number;
          discount_amount: number;
          final_amount: number;
          vat_exempted?: boolean;
          applied_by: string;
          verification_document_url?: string | null;
          created_at?: string;
        };
        Update: {
          verification_document_url?: string | null;
        };
      };

      // System Configuration
      system_config: {
        Row: {
          id: string;
          key: string;
          value: any;
          description: string | null;
          is_public: boolean;
          updated_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          value: any;
          description?: string | null;
          is_public?: boolean;
          updated_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          value?: any;
          description?: string | null;
          is_public?: boolean;
          updated_by?: string;
          updated_at?: string;
        };
      };

      // Financial Tracking
      transaction_logs: {
        Row: {
          id: string;
          booking_id: string;
          transaction_type: string;
          amount: number;
          currency: string;
          payment_method: string | null;
          payment_reference: string | null;
          status: string;
          metadata: any;
          processed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          transaction_type: string;
          amount: number;
          currency?: string;
          payment_method?: string | null;
          payment_reference?: string | null;
          status?: string;
          metadata?: any;
          processed_at?: string | null;
          created_at?: string;
        };
        Update: {
          status?: string;
          payment_reference?: string | null;
          metadata?: any;
          processed_at?: string | null;
        };
      };

      revenue_shares: {
        Row: {
          id: string;
          booking_id: string;
          operator_id: string;
          host_id: string | null;
          gross_amount: number;
          platform_fee: number;
          operator_share: number;
          host_share: number;
          net_amount: number;
          share_percentage: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          operator_id: string;
          host_id?: string | null;
          gross_amount: number;
          platform_fee: number;
          operator_share: number;
          host_share?: number;
          net_amount: number;
          share_percentage: number;
          created_at?: string;
        };
        Update: {
          // Revenue shares are typically immutable once created
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      user_type: 'client' | 'host' | 'operator' | 'admin' | 'pos';
      user_status: 'active' | 'inactive' | 'suspended';
      parking_type: 'hosted' | 'street' | 'facility';
      spot_status: 'available' | 'occupied' | 'reserved' | 'maintenance';
      booking_status:
        | 'pending'
        | 'confirmed'
        | 'active'
        | 'completed'
        | 'cancelled';
      payment_status: 'pending' | 'paid' | 'refunded';
      message_type: 'text' | 'image' | 'file';
      conversation_type: 'user_host' | 'user_operator' | 'user_support';
      rated_type: 'spot' | 'host' | 'operator' | 'user';
      ad_status: 'pending' | 'approved' | 'active' | 'paused' | 'completed';
      target_type: 'section' | 'zone';
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}
