export const Constants = {
    public: {
        Enums: {
            ad_content_type: ["image", "video", "text", "banner", "interstitial"],
            ad_status: ["pending", "approved", "active", "paused", "completed"],
            ad_target_type: ["section", "zone"],
            booking_status: [
                "pending",
                "confirmed",
                "active",
                "completed",
                "cancelled",
            ],
            conversation_type: ["user_host", "user_operator", "user_support"],
            discrepancy_type: [
                "amount_mismatch",
                "missing_revenue_share",
                "missing_transaction",
                "status_mismatch",
                "duplicate_entry",
            ],
            financial_report_type: [
                "operator_revenue",
                "host_revenue",
                "transaction_reconciliation",
                "payout_summary",
                "revenue_analysis",
            ],
            message_type: ["text", "image", "file"],
            parking_type: ["hosted", "street", "facility"],
            payment_intent_status: [
                "requires_payment_method",
                "requires_confirmation",
                "requires_action",
                "processing",
                "succeeded",
                "cancelled",
            ],
            payment_method_type: [
                "credit_card",
                "debit_card",
                "digital_wallet",
                "bank_transfer",
            ],
            payment_provider: ["stripe", "paypal", "gcash", "paymaya", "park_angel"],
            payment_status: ["pending", "paid", "refunded"],
            payment_transaction_status: [
                "pending",
                "processing",
                "succeeded",
                "failed",
                "cancelled",
                "refunded",
                "partially_refunded",
            ],
            payout_status: ["pending", "processing", "paid", "failed", "cancelled"],
            rated_type: ["spot", "host", "operator", "user"],
            reconciliation_rule_type: [
                "amount_validation",
                "status_check",
                "duplicate_detection",
                "completeness_check",
            ],
            remittance_frequency: ["daily", "weekly", "biweekly", "monthly"],
            remittance_status: [
                "pending",
                "processing",
                "completed",
                "failed",
                "cancelled",
            ],
            spot_status: ["available", "occupied", "reserved", "maintenance"],
            target_type: ["section", "zone"],
            user_status: ["active", "inactive", "suspended"],
            user_type: ["client", "host", "operator", "admin", "pos"],
            vip_type: ["vvip", "flex_vvip", "spot_vip", "spot_flex_vip"],
        },
    },
};
